# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1062, 676)
        MainWindow.setAcceptDrops(True)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    color: #fff;\n"
"}\n"
"#centralwidget{\n"
"    background-color: #1f232a;\n"
"}\n"
"#leftMenuSubContainer{\n"
"    background-color: #16191d;\n"
"}\n"
"#leftMenuSubContainer QPushButton{\n"
"    text-align: left;\n"
"    padding: 5px 10px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"}\n"
"#centerMenuSubContainer, #rightMenuSubContainer{\n"
"    background-color: #2c313c;\n"
"}\n"
"#frame_4, #frame_8, #popupNotificationSubContainer{\n"
"    background-color: #16191d;\n"
"    border-radius: 10px;\n"
"}\n"
"#headerContainer, #footerContainter{\n"
"    background-color: #2c313c;\n"
"}\n"
"")
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.username_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.username_text_edit.setGeometry(QtCore.QRect(770, 70, 181, 31))
        self.username_text_edit.setStyleSheet("QTextEdit {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.username_text_edit.setObjectName("username_text_edit")
        self.password_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.password_text_edit.setGeometry(QtCore.QRect(770, 120, 181, 31))
        self.password_text_edit.setStyleSheet("QTextEdit {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.password_text_edit.setObjectName("password_text_edit")
        self.continue_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.continue_text_edit.setGeometry(QtCore.QRect(770, 170, 181, 31))
        self.continue_text_edit.setStyleSheet("QTextEdit {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.continue_text_edit.setObjectName("continue_text_edit")
        self.signin_button_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.signin_button_text_edit.setGeometry(QtCore.QRect(770, 220, 181, 31))
        self.signin_button_text_edit.setStyleSheet("QTextEdit {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.signin_button_text_edit.setObjectName("signin_button_text_edit")
        self.browser_sessions_display_Frame = QtWidgets.QFrame(self.centralwidget)
        self.browser_sessions_display_Frame.setGeometry(QtCore.QRect(20, 10, 741, 501))
        self.browser_sessions_display_Frame.setStyleSheet("QWidget {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.browser_sessions_display_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.browser_sessions_display_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.browser_sessions_display_Frame.setObjectName("browser_sessions_display_Frame")
        self.mdiArea = QtWidgets.QMdiArea(self.browser_sessions_display_Frame)
        self.mdiArea.setGeometry(QtCore.QRect(20, 20, 701, 461))
        self.mdiArea.setActivationOrder(QtWidgets.QMdiArea.StackingOrder)
        self.mdiArea.setTabsMovable(True)
        self.mdiArea.setObjectName("mdiArea")
        self.thread_1 = QtWidgets.QWidget()
        self.thread_1.setObjectName("thread_1")
        self.thread_2 = QtWidgets.QWidget()
        self.thread_2.setObjectName("thread_2")
        self.thread_3 = QtWidgets.QWidget()
        self.thread_3.setObjectName("thread_3")
        self.thread_4 = QtWidgets.QWidget()
        self.thread_4.setObjectName("thread_4")
        self.thread_5 = QtWidgets.QWidget()
        self.thread_5.setObjectName("thread_5")
        self.start_hyperlink_button = HyperlinkButton(self.centralwidget)
        self.start_hyperlink_button.setGeometry(QtCore.QRect(790, 270, 81, 31))
        self.start_hyperlink_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(5, 234, 255);\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 204, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 153, 204);\n"
"}")
        self.start_hyperlink_button.setObjectName("start_hyperlink_button")
        self.stop_hyperlink_button = HyperlinkButton(self.centralwidget)
        self.stop_hyperlink_button.setGeometry(QtCore.QRect(880, 270, 81, 31))
        self.stop_hyperlink_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(5, 234, 255);\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 204, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 153, 204);\n"
"}")
        self.stop_hyperlink_button.setObjectName("stop_hyperlink_button")
        self.combolist_frame = QtWidgets.QFrame(self.centralwidget)
        self.combolist_frame.setGeometry(QtCore.QRect(790, 310, 261, 321))
        self.combolist_frame.setStyleSheet("QWidget {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.combolist_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.combolist_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.combolist_frame.setObjectName("combolist_frame")
        self.combolist_text_edit = QtWidgets.QTextEdit(self.combolist_frame)
        self.combolist_text_edit.setGeometry(QtCore.QRect(0, 0, 261, 321))
        self.combolist_text_edit.setObjectName("combolist_text_edit")
        self.combolist_scroll = QtWidgets.QScrollArea(self.combolist_frame)
        self.combolist_scroll.setGeometry(QtCore.QRect(0, 0, 261, 321))
        self.combolist_scroll.setWidgetResizable(True)
        self.combolist_scroll.setObjectName("combolist_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 257, 317))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.combolist_scroll.setWidget(self.scrollAreaWidgetContents)
        self.response_frame = QtWidgets.QFrame(self.centralwidget)
        self.response_frame.setGeometry(QtCore.QRect(20, 530, 541, 101))
        self.response_frame.setStyleSheet("QWidget {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.response_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.response_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.response_frame.setObjectName("response_frame")
        self.save_hyperlink_button = HyperlinkButton(self.centralwidget)
        self.save_hyperlink_button.setGeometry(QtCore.QRect(970, 270, 81, 31))
        self.save_hyperlink_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(5, 234, 255);\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 204, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 153, 204);\n"
"}")
        self.save_hyperlink_button.setObjectName("save_hyperlink_button")
        self.website_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.website_text_edit.setGeometry(QtCore.QRect(770, 20, 231, 31))
        self.website_text_edit.setStyleSheet("QTextEdit {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.website_text_edit.setObjectName("website_text_edit")
        self.password_dropdown_tool_button = QtWidgets.QComboBox(self.centralwidget)
        self.password_dropdown_tool_button.setGeometry(QtCore.QRect(960, 120, 101, 31))
        self.password_dropdown_tool_button.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    background-color: white;\n"
"    color: #333;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-left: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(https://i.imgur.com/F4LhBKH.png); /*Replace with your own arrow image*/\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: #ccc;\n"
"    color: teal;\n"
"}")
        self.password_dropdown_tool_button.setObjectName("password_dropdown_tool_button")
        self.password_dropdown_tool_button.addItem("")
        self.password_dropdown_tool_button.addItem("")
        self.password_dropdown_tool_button.addItem("")
        self.password_dropdown_tool_button.addItem("")
        self.continue_tool_button = QtWidgets.QComboBox(self.centralwidget)
        self.continue_tool_button.setGeometry(QtCore.QRect(960, 170, 101, 31))
        self.continue_tool_button.setStyleSheet("QComboBox {\n"
"    padding: 6px;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 4px;\n"
"    background-color: #f2f2f2;\n"
"    color: #333;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    background-color: transparent;\n"
"    border-left: 1px solid #ccc;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(down_arrow.png); /*Replace with your own arrow image*/\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: #007bff;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #ccc; /\n"
"\n"
"*Set the background color of the selected text*\n"
"\n"
"/\n"
"    color: #333; /*Set the color of the selected text*/\n"
"}")
        self.continue_tool_button.setObjectName("continue_tool_button")
        self.continue_tool_button.addItem("")
        self.continue_tool_button.addItem("")
        self.continue_tool_button.addItem("")
        self.continue_tool_button.addItem("")
        self.signin_dropdown_tool_button_2 = QtWidgets.QComboBox(self.centralwidget)
        self.signin_dropdown_tool_button_2.setGeometry(QtCore.QRect(960, 220, 101, 31))
        self.signin_dropdown_tool_button_2.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    background-color: white;\n"
"    color: #333;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    background-color: transparent;\n"
"    border-left: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(down_arrow.png); /*Replace with your own arrow image*/\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: #ccc;\n"
"    color: white;\n"
"}")
        self.signin_dropdown_tool_button_2.setObjectName("signin_dropdown_tool_button_2")
        self.signin_dropdown_tool_button_2.addItem("")
        self.signin_dropdown_tool_button_2.addItem("")
        self.signin_dropdown_tool_button_2.addItem("")
        self.signin_dropdown_tool_button_2.addItem("")
        self.username_dropdown_tool_button = QtWidgets.QComboBox(self.centralwidget)
        self.username_dropdown_tool_button.setGeometry(QtCore.QRect(960, 70, 101, 31))
        self.username_dropdown_tool_button.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    background-color: white;\n"
"    color: #333;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    background-color: transparent;\n"
"    border-left: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(down_arrow.png); /*Replace with your own arrow image*/\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: #ccc;\n"
"    color: white;\n"
"}")
        self.username_dropdown_tool_button.setObjectName("username_dropdown_tool_button")
        self.username_dropdown_tool_button.addItem("")
        self.username_dropdown_tool_button.addItem("")
        self.username_dropdown_tool_button.addItem("")
        self.username_dropdown_tool_button.addItem("")
        self.results_frame = QtWidgets.QFrame(self.centralwidget)
        self.results_frame.setGeometry(QtCore.QRect(580, 530, 181, 101))
        self.results_frame.setStyleSheet("QWidget {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.results_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.results_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.results_frame.setObjectName("results_frame")
        self.record_button = RadioButton(self.centralwidget)
        self.record_button.setGeometry(QtCore.QRect(1010, 20, 41, 24))
        self.record_button.setObjectName("record_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.username_text_edit.setPlaceholderText(_translate("MainWindow", "Username Element Value"))
        self.password_text_edit.setPlaceholderText(_translate("MainWindow", "Password Element Value"))
        self.continue_text_edit.setPlaceholderText(_translate("MainWindow", "Continue Button Element Value"))
        self.signin_button_text_edit.setPlaceholderText(_translate("MainWindow", "Signin Element Value"))
        self.thread_1.setWindowTitle(_translate("MainWindow", "Thread #1"))
        self.thread_2.setWindowTitle(_translate("MainWindow", "Thread #2"))
        self.thread_3.setWindowTitle(_translate("MainWindow", "Thread #3"))
        self.thread_4.setWindowTitle(_translate("MainWindow", "Thread #4"))
        self.thread_5.setWindowTitle(_translate("MainWindow", "Thread #5"))
        self.start_hyperlink_button.setText(_translate("MainWindow", "Start"))
        self.stop_hyperlink_button.setText(_translate("MainWindow", "Stop"))
        self.save_hyperlink_button.setText(_translate("MainWindow", "Save"))
        self.website_text_edit.setPlaceholderText(_translate("MainWindow", "Website URL with HTTPS://"))
        self.password_dropdown_tool_button.setItemText(0, _translate("MainWindow", "Element ID"))
        self.password_dropdown_tool_button.setItemText(1, _translate("MainWindow", "X Path"))
        self.password_dropdown_tool_button.setItemText(2, _translate("MainWindow", "ID"))
        self.password_dropdown_tool_button.setItemText(3, _translate("MainWindow", "Class"))
        self.continue_tool_button.setItemText(0, _translate("MainWindow", "Element ID"))
        self.continue_tool_button.setItemText(1, _translate("MainWindow", "X Path"))
        self.continue_tool_button.setItemText(2, _translate("MainWindow", "ID"))
        self.continue_tool_button.setItemText(3, _translate("MainWindow", "Class"))
        self.signin_dropdown_tool_button_2.setItemText(0, _translate("MainWindow", "Element ID"))
        self.signin_dropdown_tool_button_2.setItemText(1, _translate("MainWindow", "X Path"))
        self.signin_dropdown_tool_button_2.setItemText(2, _translate("MainWindow", "ID"))
        self.signin_dropdown_tool_button_2.setItemText(3, _translate("MainWindow", "Class"))
        self.username_dropdown_tool_button.setItemText(0, _translate("MainWindow", "Element ID"))
        self.username_dropdown_tool_button.setItemText(1, _translate("MainWindow", "X Path"))
        self.username_dropdown_tool_button.setItemText(2, _translate("MainWindow", "ID"))
        self.username_dropdown_tool_button.setItemText(3, _translate("MainWindow", "Class"))
        self.record_button.setText(_translate("MainWindow", "Record button"))
from qfluentwidgets import HyperlinkButton, RadioButton
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
