# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1349, 676)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    color: #fff;\n"
"}\n"
"#centralwidget{\n"
"    background-color: #1f232a;\n"
"}\n"
"#leftMenuSubContainer{\n"
"    background-color: #16191d;\n"
"}\n"
"#leftMenuSubContainer QPushButton{\n"
"    text-align: left;\n"
"    padding: 5px 10px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"}\n"
"#centerMenuSubContainer, #rightMenuSubContainer{\n"
"    background-color: #2c313c;\n"
"}\n"
"#frame_4, #frame_8, #popupNotificationSubContainer{\n"
"    background-color: #16191d;\n"
"    border-radius: 10px;\n"
"}\n"
"#headerContainer, #footerContainter{\n"
"    background-color: #2c313c;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.browser_frame = QtWidgets.QFrame(self.centralwidget)
        self.browser_frame.setGeometry(QtCore.QRect(20, 10, 1001, 501))
        self.browser_frame.setMouseTracking(True)
        self.browser_frame.setTabletTracking(True)
        self.browser_frame.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.browser_frame.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.browser_frame.setStyleSheet("QWidget {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.browser_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.browser_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.browser_frame.setObjectName("browser_frame")
        self.console_frame = QtWidgets.QFrame(self.centralwidget)
        self.console_frame.setGeometry(QtCore.QRect(20, 530, 1011, 101))
        self.console_frame.setStyleSheet("QWidget {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.console_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.console_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.console_frame.setObjectName("console_frame")
        self.console_widget_textedit = QtWidgets.QTextEdit(self.console_frame)
        self.console_widget_textedit.setGeometry(QtCore.QRect(0, 0, 1011, 111))
        self.console_widget_textedit.setObjectName("console_widget_textedit")
        self.BreadcrumbBar = BreadcrumbBar(self.centralwidget)
        self.BreadcrumbBar.setGeometry(QtCore.QRect(20, 650, 171, 19))
        self.BreadcrumbBar.setObjectName("BreadcrumbBar")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(1040, 10, 301, 621))
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolBox.setObjectName("toolBox")
        self.bruteforce_page = QtWidgets.QWidget()
        self.bruteforce_page.setGeometry(QtCore.QRect(0, 0, 301, 561))
        self.bruteforce_page.setObjectName("bruteforce_page")
        self.frame_2 = QtWidgets.QFrame(self.bruteforce_page)
        self.frame_2.setGeometry(QtCore.QRect(20, 290, 261, 271))
        self.frame_2.setStyleSheet("QWidget {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.password_text_edit = QtWidgets.QTextEdit(self.bruteforce_page)
        self.password_text_edit.setEnabled(False)
        self.password_text_edit.setGeometry(QtCore.QRect(0, 100, 181, 31))
        self.password_text_edit.setStyleSheet("QTextEdit {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.password_text_edit.setObjectName("password_text_edit")
        self.start_hyperlink_button = HyperlinkButton(self.bruteforce_page)
        self.start_hyperlink_button.setGeometry(QtCore.QRect(20, 250, 81, 31))
        self.start_hyperlink_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(5, 234, 255);\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 204, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 153, 204);\n"
"}")
        self.start_hyperlink_button.setObjectName("start_hyperlink_button")
        self.continue_tool_button = QtWidgets.QComboBox(self.bruteforce_page)
        self.continue_tool_button.setGeometry(QtCore.QRect(190, 150, 101, 31))
        self.continue_tool_button.setStyleSheet("")
        self.continue_tool_button.setObjectName("continue_tool_button")
        self.continue_tool_button.addItem("")
        self.continue_tool_button.addItem("")
        self.continue_tool_button.addItem("")
        self.continue_tool_button.addItem("")
        self.password_dropdown_tool_button = QtWidgets.QComboBox(self.bruteforce_page)
        self.password_dropdown_tool_button.setGeometry(QtCore.QRect(190, 100, 101, 31))
        self.password_dropdown_tool_button.setStyleSheet("")
        self.password_dropdown_tool_button.setObjectName("password_dropdown_tool_button")
        self.password_dropdown_tool_button.addItem("")
        self.password_dropdown_tool_button.addItem("")
        self.password_dropdown_tool_button.addItem("")
        self.password_dropdown_tool_button.addItem("")
        self.username_text_edit = QtWidgets.QTextEdit(self.bruteforce_page)
        self.username_text_edit.setEnabled(False)
        self.username_text_edit.setGeometry(QtCore.QRect(0, 50, 181, 31))
        self.username_text_edit.setStyleSheet("QTextEdit {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.username_text_edit.setObjectName("username_text_edit")
        self.website_text_edit = QtWidgets.QTextEdit(self.bruteforce_page)
        self.website_text_edit.setGeometry(QtCore.QRect(0, 0, 281, 31))
        self.website_text_edit.setStyleSheet("QTextEdit {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.website_text_edit.setObjectName("website_text_edit")
        self.continue_text_edit = QtWidgets.QTextEdit(self.bruteforce_page)
        self.continue_text_edit.setEnabled(False)
        self.continue_text_edit.setGeometry(QtCore.QRect(0, 150, 181, 31))
        self.continue_text_edit.setStyleSheet("QTextEdit {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.continue_text_edit.setObjectName("continue_text_edit")
        self.signin_button_text_edit = QtWidgets.QTextEdit(self.bruteforce_page)
        self.signin_button_text_edit.setEnabled(False)
        self.signin_button_text_edit.setGeometry(QtCore.QRect(0, 200, 181, 31))
        self.signin_button_text_edit.setStyleSheet("QTextEdit {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.signin_button_text_edit.setObjectName("signin_button_text_edit")
        self.save_hyperlink_button = HyperlinkButton(self.bruteforce_page)
        self.save_hyperlink_button.setGeometry(QtCore.QRect(200, 250, 81, 31))
        self.save_hyperlink_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(5, 234, 255);\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 204, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 153, 204);\n"
"}")
        self.save_hyperlink_button.setObjectName("save_hyperlink_button")
        self.signin_dropdown_tool_button_2 = QtWidgets.QComboBox(self.bruteforce_page)
        self.signin_dropdown_tool_button_2.setGeometry(QtCore.QRect(190, 200, 101, 31))
        self.signin_dropdown_tool_button_2.setStyleSheet("")
        self.signin_dropdown_tool_button_2.setObjectName("signin_dropdown_tool_button_2")
        self.signin_dropdown_tool_button_2.addItem("")
        self.signin_dropdown_tool_button_2.addItem("")
        self.signin_dropdown_tool_button_2.addItem("")
        self.signin_dropdown_tool_button_2.addItem("")
        self.stop_hyperlink_button = HyperlinkButton(self.bruteforce_page)
        self.stop_hyperlink_button.setGeometry(QtCore.QRect(110, 250, 81, 31))
        self.stop_hyperlink_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(5, 234, 255);\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 204, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 153, 204);\n"
"}")
        self.stop_hyperlink_button.setObjectName("stop_hyperlink_button")
        self.username_dropdown_button = QtWidgets.QComboBox(self.bruteforce_page)
        self.username_dropdown_button.setGeometry(QtCore.QRect(190, 50, 101, 31))
        self.username_dropdown_button.setStyleSheet("")
        self.username_dropdown_button.setObjectName("username_dropdown_button")
        self.username_dropdown_button.addItem("")
        self.username_dropdown_button.addItem("")
        self.username_dropdown_button.addItem("")
        self.username_dropdown_button.addItem("")
        self.toolBox.addItem(self.bruteforce_page, "")
        self.cookie_page = QtWidgets.QWidget()
        self.cookie_page.setGeometry(QtCore.QRect(0, 0, 301, 561))
        self.cookie_page.setObjectName("cookie_page")
        self.cookie_url_text_edit = QtWidgets.QTextEdit(self.cookie_page)
        self.cookie_url_text_edit.setGeometry(QtCore.QRect(10, 0, 271, 31))
        self.cookie_url_text_edit.setStyleSheet("QWidget {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.cookie_url_text_edit.setFrameShape(QtWidgets.QFrame.Box)
        self.cookie_url_text_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cookie_url_text_edit.setLineWidth(6)
        self.cookie_url_text_edit.setObjectName("cookie_url_text_edit")
        self.UserAgentComboBox = EditableComboBox(self.cookie_page)
        self.UserAgentComboBox.setGeometry(QtCore.QRect(10, 470, 291, 33))
        self.UserAgentComboBox.setObjectName("UserAgentComboBox")
        self.cookie_automation_stats_frame = QtWidgets.QFrame(self.cookie_page)
        self.cookie_automation_stats_frame.setGeometry(QtCore.QRect(10, 220, 281, 181))
        self.cookie_automation_stats_frame.setStyleSheet("QWidget {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.cookie_automation_stats_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cookie_automation_stats_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cookie_automation_stats_frame.setObjectName("cookie_automation_stats_frame")
        self.cookie_start_button = QtWidgets.QPushButton(self.cookie_page)
        self.cookie_start_button.setGeometry(QtCore.QRect(110, 530, 75, 31))
        self.cookie_start_button.setStyleSheet("QWidget {\n"
"    border: 2px solid rgb(5, 234, 255);\n"
"}")
        self.cookie_start_button.setObjectName("cookie_start_button")
        self.toolBox.addItem(self.cookie_page, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.password_text_edit.setPlaceholderText(_translate("MainWindow", "Password Element Value"))
        self.start_hyperlink_button.setText(_translate("MainWindow", "Start"))
        self.continue_tool_button.setItemText(0, _translate("MainWindow", "Element ID"))
        self.continue_tool_button.setItemText(1, _translate("MainWindow", "X Path"))
        self.continue_tool_button.setItemText(2, _translate("MainWindow", "ID"))
        self.continue_tool_button.setItemText(3, _translate("MainWindow", "Class"))
        self.password_dropdown_tool_button.setItemText(0, _translate("MainWindow", "Element ID"))
        self.password_dropdown_tool_button.setItemText(1, _translate("MainWindow", "X Path"))
        self.password_dropdown_tool_button.setItemText(2, _translate("MainWindow", "ID"))
        self.password_dropdown_tool_button.setItemText(3, _translate("MainWindow", "Class"))
        self.username_text_edit.setPlaceholderText(_translate("MainWindow", "Username Element Value"))
        self.website_text_edit.setPlaceholderText(_translate("MainWindow", "Website URL with HTTPS://"))
        self.continue_text_edit.setPlaceholderText(_translate("MainWindow", "Continue Button Element Value"))
        self.signin_button_text_edit.setPlaceholderText(_translate("MainWindow", "Signin Element Value"))
        self.save_hyperlink_button.setText(_translate("MainWindow", "Save"))
        self.signin_dropdown_tool_button_2.setItemText(0, _translate("MainWindow", "Element ID"))
        self.signin_dropdown_tool_button_2.setItemText(1, _translate("MainWindow", "X Path"))
        self.signin_dropdown_tool_button_2.setItemText(2, _translate("MainWindow", "ID"))
        self.signin_dropdown_tool_button_2.setItemText(3, _translate("MainWindow", "Class"))
        self.stop_hyperlink_button.setText(_translate("MainWindow", "Stop"))
        self.username_dropdown_button.setItemText(0, _translate("MainWindow", "Element ID"))
        self.username_dropdown_button.setItemText(1, _translate("MainWindow", "X Path"))
        self.username_dropdown_button.setItemText(2, _translate("MainWindow", "ID"))
        self.username_dropdown_button.setItemText(3, _translate("MainWindow", "Class"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.bruteforce_page), _translate("MainWindow", "Bruteforce Emulation"))
        self.cookie_url_text_edit.setPlaceholderText(_translate("MainWindow", "URL Login"))
        self.UserAgentComboBox.setPlaceholderText(_translate("MainWindow", "User Agent To Import"))
        self.cookie_start_button.setText(_translate("MainWindow", "Start"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.cookie_page), _translate("MainWindow", "Cookie Import Automation"))
from qfluentwidgets import BreadcrumbBar, EditableComboBox, HyperlinkButton
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
